# Generated by Django 2.2.4 on 2020-04-01 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='hide',
            field=models.BooleanField(default=False),
        ),
    ]
