# Generated by Django 2.2.4 on 2020-02-28 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menubar',
            options={'ordering': ['order']},
        ),
    ]
