# Generated by Django 2.2.4 on 2020-05-01 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('value', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='value',
            name='transaction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
